package ch.hsr.ifs.gcs.driver.mavlink.support

enum class NavigationFrame {
    GLOBAL,
    LOCAL_NORTH_EAST_DOWN,
    MISSION,
    GLOBAL_RELATIVE_ALTITUDE,
    LOCAL_EAST_NORTH_UP,
    GLOBAL_INT,
    GLOBAL_RELATIVE_ALTITUDE_INT,
    LOCAL_OFFSET_NORTH_EAST_DOWN,
    BODY_NORTH_EAST_DOWN,
    BODY_OFFSET_NORTH_EAST_DOWN,
    GLOBAL_TERRAIN_ALTITUDE,
    GLOBAL_TERRAIN_ALTITUDE_INT,
    BODY_FORWARD_RIGHT_DOWN,
    BODY_FORWARD_LEFT_UP,
    MOTION_CAPTURE_NORTH_EAST_DOWN,
    MOTION_CAPTURE_EAST_NORTH_UP,
    VISION_NORTH_EAST_DOWN,
    VISION_EAST_NORTH_UP,
    ESTIMATOR_NORTH_EAST_DOWN,
    ESTIMATOR_EAST_NORTH_UP,
}