language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: deploy_docs
      before_script:
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install -y python3.5
        - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.5
      script: cd doc && sudo pip3 install -r requirements.txt && ./deploy.sh
      if: branch =~ /^(master|develop)$/
