language: android
android:
  components:
    - build-tools-28.0.3
    - android-27
jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: deploy_docs
      script: cd doc && ./deploy.sh
      if: branch =~ /^(master|develop)$/
