image: fmorgner/android-sdk:latest

pipelines:
  branches:
    develop:
      - step:
          name: build
          caches:
            - gradle
          script:
            - bash ./gradlew build
      - step:
          name: test
          caches:
            - gradle
          script:
            - bash ./gradlew test
