image: fmorgner/android-sdk:latest

pipelines:
  branches:
    develop:
      - step:
          name: build
          caches:
            - gradle
          script:
            - bash ./gradlew assemble
          artifacts:
            - app/build/**
      - step:
          name: test
          caches:
            - gradle
          script:
            - bash ./gradlew test
          artifacts:
            - app/build/outputs/apk/release/*
      - step:
          name: deploy
          script:
            - find app/build/outputs/apk/release/ -name \*gcs-release\*.apk -exec curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"{}" \;
