image: fmorgner/android-sdk:latest

pipelines:
  branches:
    develop:
      - step:
          name: build
          caches:
            - gradle
          script:
            - bash ./gradlew assembleDebug
          artifacts:
            - app/build/**
      - step:
          name: test
          caches:
            - gradle
          script:
            - bash ./gradlew testDebugUnitTest
          artifacts:
            - app/build/outputs/apk/debug/*
      - step:
          name: deploy
          script:
            - find app/build/outputs/apk/debug/ -name \*gcs-debug\*.apk -exec curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"{}" -v \;
